[package]
name = "learnrustgrad"
version = "0.1.0"
edition = "2021"
authors = ["Martin Marenz <martin.marenz@gmail.com>"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptree = "0.4.0"
